version: '1.0.0'
services:
  mysql:
    image: mysql:8.0
    container_name: jaimio-mysql
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/mysql-data:/var/lib/mysql:rw
      - ./backend/pkg/db/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
    ports:
      - 3306:3306
    expose:
      - 3306
    command: --default-authentication-plugin=mysql_native_password

  api:
    depends_on:
      - mysql
    image: jaimio-api:latest
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: jaimio-api
    env_file:
      - ./backend/.env
    ports: 
      - 8080:8080
    expose:
      - 8080
    links:
      - mysql:mysql

  web:
    depends_on:
      - api
    image: jaimio-web:latest
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: jaimio-web
    ports: 
      - 3000:3000
    expose:
      - 3000