version: '1.0.0'
services:
  mysql:
    image: mysql:8.0
    container_name: jaimio-mysql
    # env_file:
      # - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_DATABASE="jaimio"
      - MYSQL_USER="root"
      - MYSQL_PASSWORD="root"
    volumes:
      - ./mysql-data:/var/lib/mysql:rw
      - ./pkg/db/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql:rw
    ports:
      - 3306:3306
    expose:
      - 3306
    command: --default-authentication-plugin=mysql_native_password

  api:
    depends_on:
      - mysql
    image: jaimio-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jaimio-api
    env_file:
      - ./.env
    ports: 
      - 8080:8080