basePath: /api/v1/
host: localhost:8080
info:
  contact: {}
  description: My portfolio website
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Jaim-io
paths: {}
swagger: "2.0"
