name: Go

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main" ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/
        
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
         
  security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/
        
    steps:
      - uses: actions/checkout@v3
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@v3
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: --json
